#ifndef COMMON_INCLUDE_FNKCONFIG_H_
#define COMMON_INCLUDE_FNKCONFIG_H_

#define COMMON_FNKCONFIG_MAGIC 0xFEED
#define COMMON_FNKCONFIG_MAGIC_LEN 2
#define COMMON_FNKCONFIG_NAMELEN 12
#define COMMON_FNKCONFIG_MAX_LIBFUNCTIONS 32

#endif